.PHONY: clean All

All:
	@echo "----------Building project:[ DxfCnc - Debug ]----------"
	@"$(MAKE)" -f  "DxfCnc.mk"
clean:
	@echo "----------Cleaning project:[ DxfCnc - Debug ]----------"
	@"$(MAKE)" -f  "DxfCnc.mk" clean
